# -*- coding: utf-8 -*-
"""dice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2Ur2vx912Yqk5QwuIgDc4Lz8IO1Hmma
"""

import random as rand

class Dice:
  def __init__(self):
    self.output = 0
    
  def roll(self):
    self.output = rand.randint(1,6)
    return self.output

class DiceProbability():
  def __init__(self, num):
    self.num = num
    self.arrA= []
    self.arrB = []
    
  def calcProbability(self):
    for i in range(self.num):
      self.arrA.append(Dice().roll())
    for i in range(1,7):
      self.arrB.append(self.arrA.count(i)/self.num)
     
  def printProbability(self):
    print('총횟수: %d' %self.num)

    for i in range(1,7):
      print('주사위 %d: %d 비율: %.3f' %(i, self.arrA.count(i), self.arrB[i-1]))

