# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cbGHkZddbtRf6cBLTrzGGpsLtWVV_-Fi
"""

import dice

N = int(input('주사위 던질 횟수를 입력하세요:'))
dice1 = dice.DiceProbability(N)
dice1.calcProbability()
dice1.printProbability()